# Generated by Django 2.0.2 on 2018-07-23 09:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='v_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 23, 9, 21, 18, 87477, tzinfo=utc), verbose_name='date published'),
        ),
    ]
