# Generated by Django 2.0.2 on 2018-07-23 12:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_movie_v_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='v_pic',
            field=models.CharField(max_length=255, verbose_name='封面图'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='v_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 23, 12, 6, 51, 467589, tzinfo=utc), verbose_name='最后更新时间'),
        ),
    ]
