# Generated by Django 2.0.2 on 2018-07-23 12:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20180723_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='v_bdpan',
            field=models.CharField(max_length=255, verbose_name='网盘链接'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='v_ed2k',
            field=models.CharField(max_length=255, verbose_name='磁力链接 1'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='v_magnet',
            field=models.CharField(max_length=255, verbose_name='磁力链接 2'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='v_name',
            field=models.CharField(max_length=255, verbose_name='电影名'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='v_pass',
            field=models.CharField(max_length=255, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='v_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 23, 12, 9, 54, 635314, tzinfo=utc), verbose_name='最后更新时间'),
        ),
    ]
