# Generated by Django 2.0.2 on 2018-07-23 12:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20180723_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='v_href',
            field=models.CharField(max_length=255, verbose_name='采集页链接'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='v_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 23, 12, 10, 26, 695922, tzinfo=utc), verbose_name='最后更新时间'),
        ),
    ]
