# Generated by Django 2.0.2 on 2018-07-28 09:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_auto_20180723_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='v_ed2k',
            field=models.CharField(blank=True, max_length=255, verbose_name='磁力链接 1'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='v_href',
            field=models.CharField(blank=True, max_length=255, verbose_name='采集页链接'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='v_magnet',
            field=models.CharField(blank=True, max_length=255, verbose_name='磁力链接 2'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='v_pass',
            field=models.CharField(blank=True, max_length=255, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='v_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 28, 9, 32, 18, 848032, tzinfo=utc), verbose_name='最后更新时间'),
        ),
    ]
