# Generated by Django 2.0.2 on 2018-08-10 03:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_auto_20180728_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='v_valid',
            field=models.IntegerField(default=1, verbose_name='网盘链接是否可用'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='v_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 10, 3, 13, 32, 6920, tzinfo=utc), verbose_name='最后更新时间'),
        ),
    ]
