# Generated by Django 2.0.2 on 2018-08-10 03:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_auto_20180810_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='v_ed2k_name',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='v_magnet_name',
        ),
        migrations.AlterField(
            model_name='movie',
            name='v_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 10, 3, 22, 4, 554406, tzinfo=utc), verbose_name='最后更新时间'),
        ),
    ]
