# Generated by Django 2.0.2 on 2018-08-10 03:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_auto_20180810_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='v_ed2k_name',
            field=models.CharField(blank=True, default='磁力链接', max_length=255, verbose_name='磁链1名称'),
        ),
        migrations.AddField(
            model_name='movie',
            name='v_magnet_name',
            field=models.CharField(blank=True, default='磁力链接', max_length=255, verbose_name='磁链2名称'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='v_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 10, 3, 22, 29, 538751, tzinfo=utc), verbose_name='最后更新时间'),
        ),
    ]
