# Generated by Django 2.0.2 on 2018-08-10 03:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_auto_20180810_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='v_text_info',
            field=models.TextField(blank=True, default='影片信息暂时为空。', verbose_name='影片介绍'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='v_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 10, 3, 38, 11, 575948, tzinfo=utc), verbose_name='最后更新时间'),
        ),
    ]
