# Generated by Django 2.0.7 on 2018-08-10 11:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_auto_20180810_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='v_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 10, 11, 39, 14, 433110, tzinfo=utc), verbose_name='最后更新时间'),
        ),
    ]
