# Generated by Django 2.0.2 on 2018-08-13 07:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0015_auto_20180810_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passwds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100, verbose_name='名称')),
                ('p_code', models.CharField(max_length=100, verbose_name='Code')),
                ('p_value', models.CharField(max_length=255, verbose_name='密码')),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='v_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 13, 7, 43, 24, 124554, tzinfo=utc), verbose_name='最后更新时间'),
        ),
    ]
