# Generated by Django 2.0.2 on 2018-08-13 09:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0016_auto_20180813_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='v_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 13, 9, 23, 30, 295194, tzinfo=utc), verbose_name='最后更新时间'),
        ),
        migrations.AlterField(
            model_name='passwds',
            name='p_code',
            field=models.PositiveIntegerField(verbose_name='调用代码'),
        ),
    ]
