# Generated by Django 2.0.2 on 2018-08-13 09:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0017_auto_20180813_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='v_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 13, 9, 25, 16, 65337, tzinfo=utc), verbose_name='最后更新时间'),
        ),
        migrations.AlterField(
            model_name='passwds',
            name='p_name',
            field=models.CharField(max_length=255, verbose_name='名称'),
        ),
    ]
