# Generated by Django 2.1 on 2018-08-19 04:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0019_auto_20180819_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='v_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 19, 4, 2, 50, 626750, tzinfo=utc), verbose_name='最后更新时间'),
        ),
    ]
