# Generated by Django 2.0.7 on 2018-08-19 08:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0022_auto_20180819_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='v_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 19, 8, 25, 21, 478121, tzinfo=utc), verbose_name='最后更新时间'),
        ),
    ]
