# Generated by Django 2.1 on 2018-08-28 05:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0023_auto_20180819_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='v_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 28, 5, 58, 3, 585147, tzinfo=utc), verbose_name='最后更新时间'),
        ),
    ]
